# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='place',
            new_name='city',
        ),
    ]
