# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-02 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('product', models.ManyToManyField(to='shop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products_list',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.OrderProductList'),
            preserve_default=False,
        ),
    ]
