# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-02 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190202_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products_list',
        ),
        migrations.AddField(
            model_name='order',
            name='products_list',
            field=models.ManyToManyField(to='shop.OrderProductList'),
        ),
        migrations.RemoveField(
            model_name='orderproductlist',
            name='product',
        ),
        migrations.AddField(
            model_name='orderproductlist',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
            preserve_default=False,
        ),
    ]
