# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-02 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190202_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='client',
        ),
    ]
