# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-04 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20190204_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartmentNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
